attrib +h *.djs
attrib +h *.acn
attrib +h *.atfi
attrib +h *.aux
attrib +h *.bbl
attrib +h *.bcf
attrib +h *.glo
attrib +h *.ist
attrib +h *.lof
attrib +h *.lot
attrib +h *.out
attrib +h *.run
attrib +h *.sbl
attrib +h *.gz
attrib +h *.toc
attrib +h *.acr
attrib +h *.alg
attrib +h *.glg
attrib +h *.gls
attrib +h *.sym
attrib +h *.blg
attrib +h *.run.xml
attrib +h *.log