attrib -h *.djs
attrib -h *.acn
attrib -h *.atfi
attrib -h *.aux
attrib -h *.bbl
attrib -h *.bcf
attrib -h *.glo
attrib -h *.ist
attrib -h *.lof
attrib -h *.lot
attrib -h *.out
attrib -h *.run
attrib -h *.sbl
attrib -h *.gz
attrib -h *.toc
attrib -h *.acr
attrib -h *.alg
attrib -h *.glg
attrib -h *.gls
attrib -h *.sym
attrib -h *.blg
attrib -h *.run.xml
attrib -h *.log

timeout 2

attrib -r *.djs
attrib -r *.acn
attrib -r *.atfi
attrib -r *.aux
attrib -r *.bbl
attrib -r *.bcf
attrib -r *.glo
attrib -r *.ist
attrib -r *.lof
attrib -r *.lot
attrib -r *.out
attrib -r *.run
attrib -r *.sbl
attrib -r *.gz
attrib -r *.toc
attrib -r *.acr
attrib -r *.alg
attrib -r *.glg
attrib -r *.gls
attrib -r *.sym
attrib -r *.blg
attrib -r *.run.xml
attrib -r *.log